/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) franka_14dof_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {7, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {10, 1, 1};

/* franka_14dof_cost_y_0_fun:(i0[14],i1[7],i2[0],i3[],i4[0])->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33;
  a00=8.2500000000000004e-02;
  a01=arg[0]? arg[0][0] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][1] : 0;
  a04=cos(a03);
  a05=(a02*a04);
  a01=sin(a01);
  a06=4.8966386501092529e-12;
  a03=sin(a03);
  a07=(a06*a03);
  a08=(a01*a07);
  a05=(a05-a08);
  a08=arg[0]? arg[0][2] : 0;
  a09=cos(a08);
  a10=(a05*a09);
  a11=(a02*a03);
  a12=(a06*a04);
  a13=(a01*a12);
  a11=(a11+a13);
  a08=sin(a08);
  a13=(a06*a08);
  a14=(a11*a13);
  a15=(a01*a08);
  a14=(a14+a15);
  a10=(a10-a14);
  a14=(a00*a10);
  a15=-3.1600000000000000e-01;
  a16=(a15*a11);
  a14=(a14-a16);
  a16=-8.2500000000000004e-02;
  a17=arg[0]? arg[0][3] : 0;
  a18=cos(a17);
  a19=(a10*a18);
  a20=(a06*a01);
  a20=(a11-a20);
  a17=sin(a17);
  a21=(a20*a17);
  a05=(a05*a08);
  a22=(a06*a09);
  a11=(a11*a22);
  a23=(a01*a09);
  a11=(a11+a23);
  a05=(a05+a11);
  a11=(a06*a17);
  a23=(a05*a11);
  a21=(a21-a23);
  a19=(a19+a21);
  a21=(a16*a19);
  a23=3.8400000000000001e-01;
  a24=(a20*a18);
  a25=(a06*a18);
  a26=(a05*a25);
  a24=(a24-a26);
  a10=(a10*a17);
  a24=(a24-a10);
  a10=(a23*a24);
  a21=(a21+a10);
  a14=(a14+a21);
  a21=8.7999999999999995e-02;
  a10=arg[0]? arg[0][4] : 0;
  a26=cos(a10);
  a27=(a19*a26);
  a10=sin(a10);
  a28=(a06*a10);
  a29=(a24*a28);
  a20=(a06*a20);
  a05=(a05+a20);
  a20=(a05*a10);
  a29=(a29-a20);
  a27=(a27+a29);
  a29=arg[0]? arg[0][5] : 0;
  a20=cos(a29);
  a30=(a27*a20);
  a31=(a06*a26);
  a32=(a24*a31);
  a33=(a05*a26);
  a32=(a32-a33);
  a19=(a19*a10);
  a32=(a32-a19);
  a29=sin(a29);
  a19=(a06*a29);
  a33=(a32*a19);
  a05=(a06*a05);
  a24=(a24+a05);
  a05=(a24*a29);
  a33=(a33+a05);
  a30=(a30+a33);
  a30=(a21*a30);
  a14=(a14+a30);
  a30=1.0700000000000000e-01;
  a33=(a06*a24);
  a33=(a33-a32);
  a33=(a06*a33);
  a05=(a06*a20);
  a32=(a32*a05);
  a24=(a24*a20);
  a32=(a32+a24);
  a27=(a27*a29);
  a32=(a32-a27);
  a33=(a33-a32);
  a33=(a30*a33);
  a14=(a14+a33);
  if (res[0]!=0) res[0][0]=a14;
  a12=(a02*a12);
  a14=(a01*a03);
  a12=(a12-a14);
  a14=(a15*a12);
  a01=(a01*a04);
  a07=(a02*a07);
  a01=(a01+a07);
  a07=(a01*a09);
  a33=(a12*a13);
  a32=(a02*a08);
  a33=(a33+a32);
  a07=(a07+a33);
  a33=(a00*a07);
  a14=(a14+a33);
  a33=(a07*a18);
  a32=(a12*a22);
  a27=(a02*a09);
  a32=(a32+a27);
  a01=(a01*a08);
  a32=(a32-a01);
  a01=(a32*a11);
  a02=(a06*a02);
  a02=(a02-a12);
  a12=(a02*a17);
  a01=(a01+a12);
  a33=(a33+a01);
  a01=(a16*a33);
  a12=(a32*a25);
  a27=(a02*a18);
  a12=(a12+a27);
  a07=(a07*a17);
  a12=(a12-a07);
  a07=(a23*a12);
  a01=(a01+a07);
  a14=(a14+a01);
  a01=(a33*a26);
  a07=(a12*a28);
  a02=(a06*a02);
  a02=(a02-a32);
  a32=(a02*a10);
  a07=(a07-a32);
  a01=(a01+a07);
  a07=(a01*a20);
  a32=(a12*a31);
  a27=(a02*a26);
  a32=(a32-a27);
  a33=(a33*a10);
  a32=(a32-a33);
  a33=(a32*a19);
  a02=(a06*a02);
  a12=(a12+a02);
  a02=(a12*a29);
  a33=(a33+a02);
  a07=(a07+a33);
  a07=(a21*a07);
  a14=(a14+a07);
  a07=(a06*a12);
  a07=(a07-a32);
  a07=(a06*a07);
  a32=(a32*a05);
  a12=(a12*a20);
  a32=(a32+a12);
  a01=(a01*a29);
  a32=(a32-a01);
  a07=(a07-a32);
  a07=(a30*a07);
  a14=(a14+a07);
  if (res[0]!=0) res[0][1]=a14;
  a14=3.3300000000000002e-01;
  a15=(a15*a04);
  a14=(a14-a15);
  a15=(a04*a13);
  a13=(a13-a15);
  a09=(a03*a09);
  a13=(a13-a09);
  a00=(a00*a13);
  a14=(a14+a00);
  a00=(a13*a18);
  a03=(a03*a08);
  a08=(a04*a22);
  a22=(a22-a08);
  a03=(a03+a22);
  a11=(a03*a11);
  a22=2.3977070069743767e-23;
  a04=(a04+a22);
  a22=(a04*a17);
  a11=(a11+a22);
  a00=(a00+a11);
  a16=(a16*a00);
  a25=(a03*a25);
  a18=(a04*a18);
  a25=(a25+a18);
  a13=(a13*a17);
  a25=(a25-a13);
  a23=(a23*a25);
  a16=(a16+a23);
  a14=(a14+a16);
  a16=(a00*a26);
  a28=(a25*a28);
  a04=(a06*a04);
  a04=(a04-a03);
  a03=(a04*a10);
  a28=(a28-a03);
  a16=(a16+a28);
  a28=(a16*a20);
  a31=(a25*a31);
  a26=(a04*a26);
  a31=(a31-a26);
  a00=(a00*a10);
  a31=(a31-a00);
  a19=(a31*a19);
  a04=(a06*a04);
  a25=(a25+a04);
  a04=(a25*a29);
  a19=(a19+a04);
  a28=(a28+a19);
  a21=(a21*a28);
  a14=(a14+a21);
  a21=(a06*a25);
  a21=(a21-a31);
  a06=(a06*a21);
  a31=(a31*a05);
  a25=(a25*a20);
  a31=(a31+a25);
  a16=(a16*a29);
  a31=(a31-a16);
  a06=(a06-a31);
  a30=(a30*a06);
  a14=(a14+a30);
  if (res[0]!=0) res[0][2]=a14;
  a14=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a14;
  a14=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a14;
  a14=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a14;
  a14=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][6]=a14;
  a14=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][7]=a14;
  a14=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][8]=a14;
  a14=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][9]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int franka_14dof_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int franka_14dof_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int franka_14dof_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void franka_14dof_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int franka_14dof_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void franka_14dof_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void franka_14dof_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void franka_14dof_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int franka_14dof_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int franka_14dof_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real franka_14dof_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* franka_14dof_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* franka_14dof_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* franka_14dof_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* franka_14dof_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int franka_14dof_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int franka_14dof_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
