/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) franka_14dof_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};
static const casadi_int casadi_s4[23] = 
  {14, 3, 0, 6, 12, 17, 0, 1,
  2, 3, 4, 5, 0, 1, 2, 3,
  4, 5, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[3] = {3, 0, 1};

/* franka_14dof_cost_y_e_fun_jac_ut_xt:(i0[14],i1[0],i2[0],i3[],i4[0])->(o0[3],o1[14x3,17nz],o2[3x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71;
  casadi_real a72, a73, a74, a75, a76, a77, a78, a79, a80, a81, a82;
  a00=8.2500000000000004e-02;
  a01=arg[0]? arg[0][0] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][1] : 0;
  a04=cos(a03);
  a05=(a02*a04);
  a01=sin(a01);
  a06=4.8966386501092529e-12;
  a03=sin(a03);
  a07=(a06*a03);
  a08=(a01*a07);
  a05=(a05-a08);
  a08=arg[0]? arg[0][2] : 0;
  a09=cos(a08);
  a10=(a05*a09);
  a11=(a02*a03);
  a12=(a06*a04);
  a13=(a01*a12);
  a11=(a11+a13);
  a08=sin(a08);
  a13=(a06*a08);
  a14=(a11*a13);
  a15=(a01*a08);
  a14=(a14+a15);
  a10=(a10-a14);
  a14=(a00*a10);
  a15=-3.1600000000000000e-01;
  a16=(a15*a11);
  a14=(a14-a16);
  a16=-8.2500000000000004e-02;
  a17=arg[0]? arg[0][3] : 0;
  a18=cos(a17);
  a19=(a10*a18);
  a20=(a06*a01);
  a21=(a11-a20);
  a17=sin(a17);
  a22=(a21*a17);
  a23=(a05*a08);
  a24=(a06*a09);
  a25=(a11*a24);
  a26=(a01*a09);
  a25=(a25+a26);
  a23=(a23+a25);
  a25=(a06*a17);
  a26=(a23*a25);
  a27=(a22-a26);
  a27=(a19+a27);
  a28=(a16*a27);
  a29=3.8400000000000001e-01;
  a30=(a21*a18);
  a31=(a06*a18);
  a32=(a23*a31);
  a30=(a30-a32);
  a32=(a10*a17);
  a30=(a30-a32);
  a32=(a29*a30);
  a28=(a28+a32);
  a14=(a14+a28);
  a28=8.7999999999999995e-02;
  a32=arg[0]? arg[0][4] : 0;
  a33=cos(a32);
  a34=(a27*a33);
  a32=sin(a32);
  a35=(a06*a32);
  a36=(a30*a35);
  a21=(a06*a21);
  a21=(a23+a21);
  a37=(a21*a32);
  a38=(a36-a37);
  a38=(a34+a38);
  a39=arg[0]? arg[0][5] : 0;
  a40=cos(a39);
  a41=(a38*a40);
  a42=(a06*a33);
  a43=(a30*a42);
  a44=(a21*a33);
  a43=(a43-a44);
  a27=(a27*a32);
  a43=(a43-a27);
  a39=sin(a39);
  a27=(a06*a39);
  a44=(a43*a27);
  a21=(a06*a21);
  a21=(a30+a21);
  a45=(a21*a39);
  a44=(a44+a45);
  a45=(a41+a44);
  a45=(a28*a45);
  a14=(a14+a45);
  a45=1.0700000000000000e-01;
  a46=(a06*a21);
  a46=(a46-a43);
  a46=(a06*a46);
  a47=(a06*a40);
  a48=(a43*a47);
  a21=(a21*a40);
  a48=(a48+a21);
  a38=(a38*a39);
  a48=(a48-a38);
  a46=(a46-a48);
  a46=(a45*a46);
  a14=(a14+a46);
  if (res[0]!=0) res[0][0]=a14;
  a14=(a02*a12);
  a46=(a01*a03);
  a14=(a14-a46);
  a46=(a15*a14);
  a38=(a01*a04);
  a21=(a02*a07);
  a49=(a38+a21);
  a50=(a49*a09);
  a51=(a14*a13);
  a52=(a02*a08);
  a51=(a51+a52);
  a52=(a50+a51);
  a53=(a00*a52);
  a46=(a46+a53);
  a53=(a52*a18);
  a54=(a14*a24);
  a55=(a02*a09);
  a54=(a54+a55);
  a49=(a49*a08);
  a54=(a54-a49);
  a49=(a54*a25);
  a55=(a06*a02);
  a56=(a55-a14);
  a57=(a56*a17);
  a49=(a49+a57);
  a57=(a53+a49);
  a58=(a16*a57);
  a59=(a54*a31);
  a60=(a56*a18);
  a59=(a59+a60);
  a52=(a52*a17);
  a59=(a59-a52);
  a52=(a29*a59);
  a58=(a58+a52);
  a46=(a46+a58);
  a58=(a57*a33);
  a52=(a59*a35);
  a56=(a06*a56);
  a56=(a56-a54);
  a60=(a56*a32);
  a61=(a52-a60);
  a61=(a58+a61);
  a62=(a61*a40);
  a63=(a59*a42);
  a64=(a56*a33);
  a63=(a63-a64);
  a57=(a57*a32);
  a63=(a63-a57);
  a57=(a63*a27);
  a56=(a06*a56);
  a56=(a59+a56);
  a64=(a56*a39);
  a57=(a57+a64);
  a64=(a62+a57);
  a64=(a28*a64);
  a46=(a46+a64);
  a64=(a06*a56);
  a64=(a64-a63);
  a64=(a06*a64);
  a65=(a63*a47);
  a56=(a56*a40);
  a65=(a65+a56);
  a61=(a61*a39);
  a65=(a65-a61);
  a64=(a64-a65);
  a64=(a45*a64);
  a46=(a46+a64);
  if (res[0]!=0) res[0][1]=a46;
  a46=3.3300000000000002e-01;
  a64=(a15*a04);
  a46=(a46-a64);
  a64=(a04*a13);
  a61=(a13-a64);
  a56=(a03*a09);
  a61=(a61-a56);
  a66=(a00*a61);
  a46=(a46+a66);
  a66=(a61*a18);
  a67=(a03*a08);
  a68=(a04*a24);
  a68=(a24-a68);
  a69=(a67+a68);
  a70=(a69*a25);
  a71=2.3977070069743767e-23;
  a71=(a04+a71);
  a72=(a71*a17);
  a70=(a70+a72);
  a72=(a66+a70);
  a73=(a16*a72);
  a74=(a69*a31);
  a75=(a71*a18);
  a74=(a74+a75);
  a61=(a61*a17);
  a74=(a74-a61);
  a61=(a29*a74);
  a73=(a73+a61);
  a46=(a46+a73);
  a73=(a72*a33);
  a61=(a74*a35);
  a71=(a06*a71);
  a71=(a71-a69);
  a69=(a71*a32);
  a75=(a61-a69);
  a75=(a73+a75);
  a76=(a75*a40);
  a77=(a74*a42);
  a78=(a71*a33);
  a77=(a77-a78);
  a72=(a72*a32);
  a77=(a77-a72);
  a72=(a77*a27);
  a71=(a06*a71);
  a71=(a74+a71);
  a78=(a71*a39);
  a72=(a72+a78);
  a78=(a76+a72);
  a78=(a28*a78);
  a46=(a46+a78);
  a78=(a06*a71);
  a78=(a78-a77);
  a78=(a06*a78);
  a79=(a77*a47);
  a71=(a71*a40);
  a79=(a79+a71);
  a75=(a75*a39);
  a79=(a79-a75);
  a78=(a78-a79);
  a78=(a45*a78);
  a46=(a46+a78);
  if (res[0]!=0) res[0][2]=a46;
  a46=(a12*a02);
  a78=(a03*a01);
  a46=(a46-a78);
  a55=(a46-a55);
  a78=(a17*a55);
  a75=(a24*a46);
  a71=(a09*a02);
  a75=(a75+a71);
  a71=(a04*a01);
  a80=(a07*a02);
  a71=(a71+a80);
  a80=(a08*a71);
  a75=(a75-a80);
  a80=(a25*a75);
  a78=(a78-a80);
  a71=(a09*a71);
  a80=(a13*a46);
  a81=(a08*a02);
  a80=(a80+a81);
  a71=(a71+a80);
  a80=(a18*a71);
  a78=(a78-a80);
  a80=(a16*a78);
  a81=(a18*a55);
  a82=(a31*a75);
  a81=(a81-a82);
  a82=(a17*a71);
  a81=(a81+a82);
  a82=(a29*a81);
  a80=(a80+a82);
  a71=(a00*a71);
  a46=(a15*a46);
  a71=(a71+a46);
  a80=(a80-a71);
  a71=(a33*a78);
  a46=(a35*a81);
  a55=(a06*a55);
  a75=(a75+a55);
  a55=(a32*a75);
  a46=(a46-a55);
  a71=(a71+a46);
  a46=(a40*a71);
  a55=(a42*a81);
  a82=(a33*a75);
  a55=(a55-a82);
  a78=(a32*a78);
  a55=(a55-a78);
  a78=(a27*a55);
  a75=(a06*a75);
  a81=(a81+a75);
  a75=(a39*a81);
  a78=(a78+a75);
  a46=(a46+a78);
  a46=(a28*a46);
  a80=(a80+a46);
  a46=(a06*a81);
  a46=(a46-a55);
  a46=(a06*a46);
  a55=(a47*a55);
  a81=(a40*a81);
  a55=(a55+a81);
  a71=(a39*a71);
  a55=(a55-a71);
  a46=(a46-a55);
  a46=(a45*a46);
  a80=(a80+a46);
  if (res[1]!=0) res[1][0]=a80;
  a80=(a17*a05);
  a46=(a24*a05);
  a55=(a08*a11);
  a46=(a46-a55);
  a55=(a25*a46);
  a80=(a80-a55);
  a11=(a09*a11);
  a55=(a13*a05);
  a11=(a11+a55);
  a55=(a18*a11);
  a80=(a80-a55);
  a55=(a16*a80);
  a71=(a18*a05);
  a81=(a31*a46);
  a71=(a71-a81);
  a81=(a17*a11);
  a71=(a71+a81);
  a81=(a29*a71);
  a55=(a55+a81);
  a11=(a00*a11);
  a81=(a15*a05);
  a11=(a11+a81);
  a55=(a55-a11);
  a11=(a33*a80);
  a81=(a35*a71);
  a05=(a06*a05);
  a46=(a46+a05);
  a05=(a32*a46);
  a81=(a81-a05);
  a11=(a11+a81);
  a81=(a40*a11);
  a05=(a42*a71);
  a78=(a33*a46);
  a05=(a05-a78);
  a80=(a32*a80);
  a05=(a05-a80);
  a80=(a27*a05);
  a46=(a06*a46);
  a71=(a71+a46);
  a46=(a39*a71);
  a80=(a80+a46);
  a81=(a81+a80);
  a81=(a28*a81);
  a55=(a55+a81);
  a81=(a06*a71);
  a81=(a81-a05);
  a81=(a06*a81);
  a05=(a47*a05);
  a71=(a40*a71);
  a05=(a05+a71);
  a11=(a39*a11);
  a05=(a05-a11);
  a81=(a81-a05);
  a81=(a45*a81);
  a55=(a55+a81);
  if (res[1]!=0) res[1][1]=a55;
  a55=(a17*a23);
  a81=(a31*a10);
  a55=(a55-a81);
  a81=(a29*a55);
  a05=(a18*a23);
  a11=(a25*a10);
  a05=(a05+a11);
  a11=(a16*a05);
  a81=(a81-a11);
  a23=(a00*a23);
  a81=(a81-a23);
  a23=(a35*a55);
  a11=(a32*a10);
  a23=(a23-a11);
  a11=(a33*a05);
  a23=(a23-a11);
  a11=(a40*a23);
  a71=(a42*a55);
  a80=(a33*a10);
  a71=(a71-a80);
  a05=(a32*a05);
  a71=(a71+a05);
  a05=(a27*a71);
  a10=(a06*a10);
  a55=(a55+a10);
  a10=(a39*a55);
  a05=(a05+a10);
  a11=(a11+a05);
  a11=(a28*a11);
  a81=(a81+a11);
  a11=(a06*a55);
  a11=(a11-a71);
  a11=(a06*a11);
  a71=(a47*a71);
  a55=(a40*a55);
  a71=(a71+a55);
  a23=(a39*a23);
  a71=(a71-a23);
  a11=(a11-a71);
  a11=(a45*a11);
  a81=(a81+a11);
  if (res[1]!=0) res[1][2]=a81;
  a81=(a16*a30);
  a26=(a26-a22);
  a26=(a26-a19);
  a19=(a29*a26);
  a81=(a81+a19);
  a19=(a33*a30);
  a22=(a35*a26);
  a19=(a19+a22);
  a22=(a40*a19);
  a11=(a42*a26);
  a30=(a32*a30);
  a11=(a11-a30);
  a30=(a27*a11);
  a71=(a39*a26);
  a30=(a30+a71);
  a22=(a22+a30);
  a22=(a28*a22);
  a81=(a81+a22);
  a22=(a06*a26);
  a22=(a22-a11);
  a22=(a06*a22);
  a11=(a47*a11);
  a26=(a40*a26);
  a11=(a11+a26);
  a19=(a39*a19);
  a11=(a11-a19);
  a22=(a22-a11);
  a22=(a45*a22);
  a81=(a81+a22);
  if (res[1]!=0) res[1][3]=a81;
  a81=(a40*a43);
  a37=(a37-a36);
  a37=(a37-a34);
  a34=(a27*a37);
  a81=(a81+a34);
  a81=(a28*a81);
  a34=(a06*a37);
  a37=(a47*a37);
  a43=(a39*a43);
  a37=(a37-a43);
  a34=(a34+a37);
  a34=(a45*a34);
  a81=(a81-a34);
  if (res[1]!=0) res[1][4]=a81;
  a48=(a28*a48);
  a44=(a44+a41);
  a44=(a45*a44);
  a48=(a48+a44);
  if (res[1]!=0) res[1][5]=a48;
  a48=(a04*a02);
  a44=(a07*a01);
  a48=(a48-a44);
  a44=(a09*a48);
  a12=(a12*a01);
  a02=(a03*a02);
  a12=(a12+a02);
  a02=(a13*a12);
  a41=(a08*a01);
  a02=(a02+a41);
  a44=(a44-a02);
  a02=(a00*a44);
  a41=(a15*a12);
  a02=(a02-a41);
  a41=(a18*a44);
  a20=(a12-a20);
  a81=(a17*a20);
  a12=(a24*a12);
  a01=(a09*a01);
  a12=(a12+a01);
  a48=(a08*a48);
  a12=(a12+a48);
  a48=(a25*a12);
  a81=(a81-a48);
  a41=(a41+a81);
  a81=(a16*a41);
  a48=(a18*a20);
  a01=(a31*a12);
  a48=(a48-a01);
  a44=(a17*a44);
  a48=(a48-a44);
  a44=(a29*a48);
  a81=(a81+a44);
  a02=(a02+a81);
  a81=(a33*a41);
  a44=(a35*a48);
  a20=(a06*a20);
  a20=(a20+a12);
  a12=(a32*a20);
  a44=(a44-a12);
  a81=(a81+a44);
  a44=(a40*a81);
  a12=(a42*a48);
  a01=(a33*a20);
  a12=(a12-a01);
  a41=(a32*a41);
  a12=(a12-a41);
  a41=(a27*a12);
  a20=(a06*a20);
  a48=(a48+a20);
  a20=(a39*a48);
  a41=(a41+a20);
  a44=(a44+a41);
  a44=(a28*a44);
  a02=(a02+a44);
  a44=(a06*a48);
  a44=(a44-a12);
  a44=(a06*a44);
  a12=(a47*a12);
  a48=(a40*a48);
  a12=(a12+a48);
  a81=(a39*a81);
  a12=(a12-a81);
  a44=(a44-a12);
  a44=(a45*a44);
  a02=(a02+a44);
  if (res[1]!=0) res[1][6]=a02;
  a02=(a09*a14);
  a21=(a21+a38);
  a38=(a13*a21);
  a02=(a02-a38);
  a38=(a00*a02);
  a44=(a15*a21);
  a38=(a38-a44);
  a44=(a18*a02);
  a12=(a17*a21);
  a81=(a24*a21);
  a14=(a08*a14);
  a81=(a81+a14);
  a14=(a25*a81);
  a12=(a12-a14);
  a44=(a44+a12);
  a12=(a16*a44);
  a14=(a18*a21);
  a48=(a31*a81);
  a14=(a14-a48);
  a02=(a17*a02);
  a14=(a14-a02);
  a02=(a29*a14);
  a12=(a12+a02);
  a38=(a38+a12);
  a12=(a33*a44);
  a02=(a35*a14);
  a21=(a06*a21);
  a21=(a21+a81);
  a81=(a32*a21);
  a02=(a02-a81);
  a12=(a12+a02);
  a02=(a40*a12);
  a81=(a42*a14);
  a48=(a33*a21);
  a81=(a81-a48);
  a44=(a32*a44);
  a81=(a81-a44);
  a44=(a27*a81);
  a21=(a06*a21);
  a14=(a14+a21);
  a21=(a39*a14);
  a44=(a44+a21);
  a02=(a02+a44);
  a02=(a28*a02);
  a38=(a38+a02);
  a02=(a06*a14);
  a02=(a02-a81);
  a02=(a06*a02);
  a81=(a47*a81);
  a14=(a40*a14);
  a81=(a81+a14);
  a12=(a39*a12);
  a81=(a81-a12);
  a02=(a02-a81);
  a02=(a45*a02);
  a38=(a38+a02);
  if (res[1]!=0) res[1][7]=a38;
  a38=(a00*a54);
  a02=(a18*a54);
  a51=(a51+a50);
  a50=(a25*a51);
  a02=(a02-a50);
  a50=(a16*a02);
  a81=(a31*a51);
  a54=(a17*a54);
  a81=(a81+a54);
  a54=(a29*a81);
  a50=(a50-a54);
  a38=(a38+a50);
  a50=(a33*a02);
  a54=(a35*a81);
  a12=(a32*a51);
  a54=(a54+a12);
  a50=(a50-a54);
  a54=(a40*a50);
  a12=(a06*a51);
  a12=(a12-a81);
  a14=(a39*a12);
  a81=(a42*a81);
  a51=(a33*a51);
  a81=(a81+a51);
  a02=(a32*a02);
  a81=(a81+a02);
  a02=(a27*a81);
  a14=(a14-a02);
  a54=(a54+a14);
  a54=(a28*a54);
  a38=(a38+a54);
  a54=(a06*a12);
  a54=(a54+a81);
  a54=(a06*a54);
  a12=(a40*a12);
  a81=(a47*a81);
  a12=(a12-a81);
  a50=(a39*a50);
  a12=(a12-a50);
  a54=(a54-a12);
  a54=(a45*a54);
  a38=(a38+a54);
  if (res[1]!=0) res[1][8]=a38;
  a38=(a16*a59);
  a49=(a49+a53);
  a53=(a29*a49);
  a38=(a38-a53);
  a53=(a33*a59);
  a54=(a35*a49);
  a53=(a53-a54);
  a54=(a40*a53);
  a12=(a42*a49);
  a59=(a32*a59);
  a12=(a12+a59);
  a59=(a27*a12);
  a50=(a39*a49);
  a59=(a59+a50);
  a54=(a54-a59);
  a54=(a28*a54);
  a38=(a38+a54);
  a54=(a06*a49);
  a54=(a12-a54);
  a54=(a06*a54);
  a12=(a47*a12);
  a49=(a40*a49);
  a12=(a12+a49);
  a53=(a39*a53);
  a12=(a12+a53);
  a54=(a54+a12);
  a54=(a45*a54);
  a38=(a38+a54);
  if (res[1]!=0) res[1][9]=a38;
  a38=(a40*a63);
  a60=(a60-a52);
  a60=(a60-a58);
  a58=(a27*a60);
  a38=(a38+a58);
  a38=(a28*a38);
  a58=(a06*a60);
  a60=(a47*a60);
  a63=(a39*a63);
  a60=(a60-a63);
  a58=(a58+a60);
  a58=(a45*a58);
  a38=(a38-a58);
  if (res[1]!=0) res[1][10]=a38;
  a65=(a28*a65);
  a57=(a57+a62);
  a57=(a45*a57);
  a65=(a65+a57);
  if (res[1]!=0) res[1][11]=a65;
  a15=(a15*a03);
  a65=(a13*a03);
  a09=(a09*a04);
  a65=(a65-a09);
  a09=(a00*a65);
  a15=(a15+a09);
  a09=(a18*a65);
  a08=(a08*a04);
  a24=(a24*a03);
  a08=(a08+a24);
  a24=(a25*a08);
  a04=(a17*a03);
  a24=(a24-a04);
  a09=(a09+a24);
  a24=(a16*a09);
  a04=(a31*a08);
  a03=(a18*a03);
  a04=(a04-a03);
  a65=(a17*a65);
  a04=(a04-a65);
  a65=(a29*a04);
  a24=(a24+a65);
  a15=(a15+a24);
  a24=(a33*a09);
  a65=(a35*a04);
  a07=(a07+a08);
  a08=(a32*a07);
  a65=(a65+a08);
  a24=(a24+a65);
  a65=(a40*a24);
  a08=(a42*a04);
  a03=(a33*a07);
  a08=(a08+a03);
  a09=(a32*a09);
  a08=(a08-a09);
  a09=(a27*a08);
  a07=(a06*a07);
  a04=(a04-a07);
  a07=(a39*a04);
  a09=(a09+a07);
  a65=(a65+a09);
  a65=(a28*a65);
  a15=(a15+a65);
  a65=(a06*a04);
  a65=(a65-a08);
  a65=(a06*a65);
  a08=(a47*a08);
  a04=(a40*a04);
  a08=(a08+a04);
  a24=(a39*a24);
  a08=(a08-a24);
  a65=(a65-a08);
  a65=(a45*a65);
  a15=(a15+a65);
  if (res[1]!=0) res[1][12]=a15;
  a68=(a68+a67);
  a00=(a00*a68);
  a18=(a18*a68);
  a64=(a64-a13);
  a56=(a56+a64);
  a25=(a25*a56);
  a18=(a18+a25);
  a25=(a16*a18);
  a31=(a31*a56);
  a17=(a17*a68);
  a31=(a31-a17);
  a17=(a29*a31);
  a25=(a25+a17);
  a00=(a00+a25);
  a25=(a33*a18);
  a17=(a35*a31);
  a68=(a32*a56);
  a17=(a17+a68);
  a25=(a25+a17);
  a17=(a40*a25);
  a68=(a42*a31);
  a64=(a33*a56);
  a68=(a68+a64);
  a18=(a32*a18);
  a68=(a68-a18);
  a18=(a27*a68);
  a56=(a06*a56);
  a31=(a31-a56);
  a56=(a39*a31);
  a18=(a18+a56);
  a17=(a17+a18);
  a17=(a28*a17);
  a00=(a00+a17);
  a17=(a06*a31);
  a17=(a17-a68);
  a17=(a06*a17);
  a68=(a47*a68);
  a31=(a40*a31);
  a68=(a68+a31);
  a25=(a39*a25);
  a68=(a68-a25);
  a17=(a17-a68);
  a17=(a45*a17);
  a00=(a00+a17);
  if (res[1]!=0) res[1][13]=a00;
  a16=(a16*a74);
  a70=(a70+a66);
  a29=(a29*a70);
  a16=(a16-a29);
  a33=(a33*a74);
  a35=(a35*a70);
  a33=(a33-a35);
  a35=(a40*a33);
  a42=(a42*a70);
  a32=(a32*a74);
  a42=(a42+a32);
  a32=(a27*a42);
  a74=(a39*a70);
  a32=(a32+a74);
  a35=(a35-a32);
  a35=(a28*a35);
  a16=(a16+a35);
  a35=(a06*a70);
  a35=(a42-a35);
  a35=(a06*a35);
  a42=(a47*a42);
  a70=(a40*a70);
  a42=(a42+a70);
  a33=(a39*a33);
  a42=(a42+a33);
  a35=(a35+a42);
  a35=(a45*a35);
  a16=(a16+a35);
  if (res[1]!=0) res[1][14]=a16;
  a40=(a40*a77);
  a69=(a69-a61);
  a69=(a69-a73);
  a27=(a27*a69);
  a40=(a40+a27);
  a40=(a28*a40);
  a06=(a06*a69);
  a47=(a47*a69);
  a39=(a39*a77);
  a47=(a47-a39);
  a06=(a06+a47);
  a06=(a45*a06);
  a40=(a40-a06);
  if (res[1]!=0) res[1][15]=a40;
  a28=(a28*a79);
  a72=(a72+a76);
  a45=(a45*a72);
  a28=(a28+a45);
  if (res[1]!=0) res[1][16]=a28;
  return 0;
}

CASADI_SYMBOL_EXPORT int franka_14dof_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int franka_14dof_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int franka_14dof_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void franka_14dof_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int franka_14dof_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void franka_14dof_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void franka_14dof_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void franka_14dof_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int franka_14dof_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int franka_14dof_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real franka_14dof_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* franka_14dof_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* franka_14dof_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* franka_14dof_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* franka_14dof_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int franka_14dof_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int franka_14dof_cost_y_e_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
